# Generated by Django 3.2.5 on 2021-07-24 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import interface.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='userModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('works_at', models.CharField(blank=True, max_length=110, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='campusData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('students_csv', models.FileField(null=True, upload_to=interface.models.set_upload_path)),
                ('staff_csv', models.FileField(null=True, upload_to=interface.models.set_upload_path)),
                ('mess_csv', models.FileField(null=True, upload_to=interface.models.set_upload_path)),
                ('timetable_csv', models.FileField(null=True, upload_to=interface.models.set_upload_path)),
                ('common_areas_csv', models.FileField(null=True, upload_to=interface.models.set_upload_path)),
                ('classes_csv', models.FileField(null=True, upload_to=interface.models.set_upload_path)),
                ('campus_name', models.CharField(max_length=20, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='campusInstantiation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_json', models.FileField(null=True, upload_to=interface.models.set_instantiation_filePath)),
                ('interaction_spaces_json', models.FileField(null=True, upload_to=interface.models.set_instantiation_filePath)),
                ('trans_coeff_file', models.JSONField(null=True)),
                ('status', models.CharField(choices=[('Created', 'Created'), ('Running', 'Running'), ('Complete', 'Complete'), ('Error', 'Error')], default='Created', max_length=10, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('inst_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='interface.campusdata')),
            ],
        ),
        migrations.CreateModel(
            name='interventions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intv_name', models.CharField(max_length=30, null=True)),
                ('intv_json', models.JSONField(null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegisterOrigin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField()),
                ('redirect_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='UserRegisterToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='testingParams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testing_protocol_name', models.CharField(max_length=30, null=True)),
                ('testing_protocol_file', models.JSONField(null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='simulationParams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simulation_name', models.CharField(max_length=30, null=True)),
                ('days_to_simulate', models.PositiveSmallIntegerField(default=100, null=True)),
                ('init_infected_seed', models.PositiveSmallIntegerField(default=200, null=True)),
                ('simulation_iterations', models.PositiveSmallIntegerField(default=10, null=True)),
                ('enable_testing', models.BooleanField(default=True)),
                ('output_directory', models.CharField(max_length=500, null=True)),
                ('testing_capacity', models.PositiveSmallIntegerField(default=100, null=True)),
                ('periodicity', models.PositiveSmallIntegerField(default=7, null=True)),
                ('betaScale', models.PositiveSmallIntegerField(default=9, null=True)),
                ('min_grp_size', models.PositiveSmallIntegerField(default=10, null=True)),
                ('max_grp_size', models.PositiveSmallIntegerField(default=15, null=True)),
                ('avg_associations', models.PositiveSmallIntegerField(default=5, null=True)),
                ('minimum_hostel_time', models.DecimalField(decimal_places=5, default=1.0, max_digits=9, null=True)),
                ('status', models.CharField(choices=[('Created', 'Created'), ('Running', 'Running'), ('Complete', 'Complete'), ('Error', 'Error')], default='Created', max_length=10, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('completed_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('campus_instantiation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='interface.campusinstantiation')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('intervention', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='interface.interventions')),
                ('testing_protocol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='interface.testingparams')),
            ],
        ),
        migrations.CreateModel(
            name='simulationResults',
            fields=[
                ('simulation_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='interface.simulationparams')),
                ('agg_results', models.JSONField(null=True)),
                ('status', models.CharField(default='NA', max_length=3)),
                ('completed_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
